"use strict";
const $=s=>document.querySelector(s), DB="moderns-reader", STORE="books"; let books=[],current=null,section=0;
function db(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:"id"});r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function all(){const d=await db();return new Promise(ok=>{const r=d.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>ok(r.result)})}
async function put(v){const d=await db();return new Promise(ok=>{const r=d.transaction(STORE,"readwrite").objectStore(STORE).put(v);r.onsuccess=ok})}
const text=(doc,sel)=>doc.querySelector(sel)?.textContent?.trim()||"";
async function parse(file){if(!window.JSZip)throw Error("EPUB importer is not cached yet. Open the app online once.");const zip=await JSZip.loadAsync(file);const parser=new DOMParser();const container=parser.parseFromString(await zip.file("META-INF/container.xml").async("text"),"application/xml");const opfPath=container.querySelector("rootfile").getAttribute("full-path"),base=opfPath.split("/").slice(0,-1).join("/");const opf=parser.parseFromString(await zip.file(opfPath).async("text"),"application/xml"),items={};opf.querySelectorAll("manifest item").forEach(i=>items[i.getAttribute("id")]={href:i.getAttribute("href"),type:i.getAttribute("media-type")});const sections=[];for(const ref of opf.querySelectorAll("spine itemref")){const item=items[ref.getAttribute("idref")];if(!item)continue;const path=[base,item.href].filter(Boolean).join("/");const f=zip.file(path);if(!f)continue;const doc=parser.parseFromString(await f.async("text"),"text/html");doc.querySelectorAll("script,style,img,svg,video,audio").forEach(x=>x.remove());sections.push({title:text(doc,"h1,h2,h3")||`Section ${sections.length+1}`,html:doc.body.innerHTML})}return{id:crypto.randomUUID(),title:text(opf,"metadata title, dc\\:title")||file.name.replace(/\\.epub$/i,""),author:text(opf,"metadata creator, dc\\:creator")||"Unknown author",sections,position:0,added:Date.now()}}
async function renderLibrary(){books=await all();$("#books").innerHTML=books.length?books.map(b=>`<div class="book" data-id="${b.id}"><h2>${esc(b.title)}</h2><p>${esc(b.author)}</p><small>${b.sections.length} sections · ${Math.round(((b.position||0)+1)/b.sections.length*100)}%</small></div>`).join(""):"";document.querySelectorAll(".book").forEach(x=>x.onclick=()=>openBook(x.dataset.id))}
function esc(s){const d=document.createElement("div");d.textContent=s;return d.innerHTML}
function openBook(id){current=books.find(b=>b.id===id);section=current.position||0;$("#library").hidden=true;$("#reader").hidden=false;$("#library-btn").hidden=false;show()}
async function show(){const s=current.sections[section];$("#title").textContent=current.title;$("#subtitle").textContent=s.title;$("#content").innerHTML=s.html;$("#progress").textContent=`${section+1} / ${current.sections.length}`;current.position=section;await put(current);scrollTo(0,0)}
$("#file").onchange=async e=>{for(const f of e.target.files){try{await put(await parse(f))}catch(err){alert(err.message)}}renderLibrary()};$("#prev").onclick=()=>{if(section>0){section--;show()}};$("#next").onclick=()=>{if(section<current.sections.length-1){section++;show()}};$("#library-btn").onclick=()=>{$("#reader").hidden=true;$("#library").hidden=false;$("#library-btn").hidden=true;$("#title").textContent="Moderns Reader";$("#subtitle").textContent="A private offline library";renderLibrary()};$("#settings-btn").onclick=()=>$("#settings").showModal();$("#close-settings").onclick=()=>$("#settings").close();$("#theme").onclick=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==="light"?"dark":"light";localStorage.theme=document.documentElement.dataset.theme};$("#font-size").oninput=e=>document.documentElement.style.setProperty("--size",e.target.value+"px");$("#line-height").oninput=e=>document.documentElement.style.setProperty("--line",e.target.value/10);document.documentElement.dataset.theme=localStorage.theme||"dark";if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").then(()=>$("#offline").textContent=navigator.onLine?"Offline ready":"Offline mode");addEventListener("offline",()=>$("#offline").textContent="Offline mode");renderLibrary();
